name: eyonexis-dev

services:
  db:
    image: postgres:17
    container_name: eyonexis-database-dev
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
    ports:
      - "5433:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - web
      - internal

volumes:
  db_data:

networks:
  web:
    external: true
    name: web
  internal:
    internal: true
